from setuptools import setup


with open('README.md', 'r', encoding='utf-8') as readme_file:
    # Remove GitHub dark mode images for PyPI
    DARKMODE_ATTR = 'media="(prefers-color-scheme: dark)"'

    DESCRIPTION = (
        # GitHub Flavored Markdown comment
        "<!-- THIS FILE IS AUTOGENERATED -->\n"
        "<!-- DO NOT EDIT IT OR TRACK IT WITH VCS -->\n\n"
    ) + ''.join(line for line in readme_file if DARKMODE_ATTR not in line)


setup(long_description=DESCRIPTION)
